server:
  port: 8081
spring:
  application:
    name: fraudMS
  #Connect with PG-Admin    http://localhost:5050/browser/
  datasource:
    username: 'shalnark'
    password: 'password'
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true